# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pred_rating', models.CharField(max_length=20)),
                ('real_rating', models.CharField(max_length=20)),
                ('rating_words', models.CharField(max_length=200)),
                ('cloud_words', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
